# ArgoCD Config Management Plugin v2 specification
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: envsubst
spec:
  version: v1.0
  # Plugin must be explicitly specified in Application manifest
  # No auto-discovery - this follows ArgoCD best practices
  generate:
    command: ["/usr/local/bin/argocd-envsubst-plugin", "generate"]