# ArgoCD Config Management Plugin v2 specification
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: kustomize-envsubst
spec:
  version: v1.0
  # Discovery rules - when to use this plugin
  discover:
    find:
      # Match directories with kustomization.yaml OR any YAML files
      command: ["sh", "-c", "find . -name 'kustomization.yaml' -o -name '*.yaml' -o -name '*.yml' | head -1"]
  # How to generate manifests
  generate:
    command: ["/usr/local/bin/argocd-envsubst-plugin", "generate"]