# ArgoCD Config Management Plugin v2 specification
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: argocd-envsubst-plugin
spec:
  version: v1.0
  # Discovery rules to ensure all files are available to the plugin
  discover:
    find:
      glob: "**/kustomization.yaml"
  generate:
    command: ["/usr/local/bin/argocd-envsubst-plugin", "generate"]
  # Preserve all files when copying to plugin
  # This ensures kustomization.yaml and other files are available
  preserveFileMode: true